repos:
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.5
    hooks:
      - id: ruff
      - id: ruff-format
        args: [--check, --diff]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements

# Replace commitsar with conventional commit checker
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # default: [feat, fix, ci, chore, docs, style, refactor, perf, test, build, revert]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    - id: python-check-blanket-noqa
    - id: python-no-eval

  - repo: local
    hooks:
      - id: forbid-categorical
        name: Prevent usage of categorical
        types: [text]
        entry: categorical
        args: ['-i']
        language: pygrep
        exclude: \.pre-commit-config\.yaml$

  - repo: local
    hooks:
      - id: forbid-numerical
        name: Prevent usage of numerical
        types: [text]
        entry: numerical
        args: ['-i']
        language: pygrep
        exclude: \.pre-commit-config\.yaml$
